AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Webhook handler for Zenhub Automatic card movement based on Github events

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  zenhubToken:
    Type: String
  githubToken:
    Type: String
  githubWebhookSecret:
    Type: String
  isReopened:
    Type: String
    Default: ""
  isClosed:
    Type: String
    Default: ""
  prOpened:
    Type: String
    Default: ""
  prReopened:
    Type: String
    Default: ""
  prRevreq:
    Type: String
    Default: ""
  prMerged:
    Type: String
    Default: ""
  prClosed:
    Type: String
    Default: ""
  newBranch:
    Type: String
    Default: ""
    
Resources:
  ZhGhWhFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: zhghwh/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - arm64
      FunctionUrlConfig:
        AuthType: NONE
      Events:
        ZhGhWh:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /from_github
            Method: post
      Environment:
        Variables:
          zenhubToken: !Ref zenhubToken 
          githubToken: !Ref githubToken
          githubWebhookSecret: !Ref githubWebhookSecret
          isReopened: !Ref isReopened
          isClosed: !Ref isClosed
          prOpened: !Ref prOpened
          prReopened: !Ref prReopened
          prRevreq: !Ref prRevreq
          prMerged: !Ref prMerged
          prClosed: !Ref prClosed
          newBranch: !Ref newBranch

Outputs:
  ZhGhWhFunctionEndpoint:
    Description: "zhghwh handler Lambda Function endpoint"
    Value: Fn::Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com"
  ZhGhWhFunction:
    Description: "zhghwh handler Lambda Function ARN"
    Value: Fn::GetAtt ZhGhWhFunction.Arn
  ZhGhWhFunctionIamRole:
    Description: "Implicit IAM Role created for zhghwh handler function"
    Value: Fn::GetAtt ZhGhWhFunctionRole.Arn
    
